version: "3.9"

services:
  postgres:
    container_name: postgres
    build: ./docker_build/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pyprod
    restart: on-failure

  back:
    container_name: back
    build:
      context: .
      dockerfile: ./docker_build/back/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/pyprod/
    depends_on:
      - postgres
    env_file: .env
    extra_hosts:
      - ${host_docker_internal:-host_docker_internal}:host-gateway
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  postgres_db:
